# Generated by Django 2.1.7 on 2019-02-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='typr',
            new_name='type',
        ),
    ]
